```
---
title: 'Corti加强领导团队，与战略高管增强团队'
date: 2024-09-13
author: ByteAILab
---

The move comes as Corti doubles down on its mission to transform overburdened healthcare systems with accessible and trustworthy AI
Corti, the global AI engine designed for healthcare, is bolstering its leadership team with the addition of three more senior executives. The strategic move furthers the company’s mission of helping billions of people benefit from low risk, high quality care through its safe and effective Generative AI, woven into the fabric of every patient interaction around the world.
Following a period of rapid growth for the business – which had processed more than 100 million patient interactions – Corti is now welcoming new talent from some of the world’s biggest organisations to help continue its expansion.
Chad Compton joins Corti as Chief Revenue Officer from Microsoft’s leadership team. Prior to Microsoft, Chad was a key executive at Nuance, which was acquired by Microsoft in 2022 for $19.7 billion. At Nuance, he oversaw one of the world’s most successful healthcare partnership sales teams, generating hundreds of millions of dollars in revenue. In his new role at Corti, Chad will leverage his extensive experience to drive growth across the global market.
Frederik Brabant, MD will step into the role of Chief Medical Strategy Officer. Previously, Frederik served as the chief medical information officer and VP of international healthcare partnerships at Microsoft Nuance. With nearly a decade of leadership experience at Nuance, Frederik played a pivotal role in driving the success of flagship products such as Dragon Dictation and leading global partnership initiatives worth over millions. His role at Corti will be instrumental in shaping the company’s medical strategy and expanding its global footprint.
Yvonne Kirsch is Corti’s new VP Partnerships, North America, coming from Philips Speech, where she was running the North American Unit. Yvonne’s experience in building strategic partnerships and driving business growth will power Corti’s next chapter in the region, where Corti is on track to process more than 100 million patient interactions annually by 2025.
These three new additions to the Corti team builds on a series of other recent hires from Microsoft Nuance and Philips Speech, including Milko Jovanoski, now VP of partnerships for Europe, and Robert Lamprell, UK commercial director, who previously held positions as international marketing director and senior account director at Microsoft Nuance, respectively. Last week, Mikaël Grynszpan also joined the Corti team from Philips Speech as Director of Sales in France, following in the footsteps of Yvonne Kirsch and Corti’s CPO, Florian Schwieker, who also made the move from Philips Speech to Corti.
Speaking about the new hires, Andreas Cleve, co-founder and CEO of Corti, said: “These critical hires mark a significant milestone for Corti as we continue to scale our impact across healthcare. When top commercial talent moves from such major companies to the promising new incumbent, it marks the start of a new era. Welcoming such unparalleled expertise to the team will be invaluable as we continue to innovate and expand our global reach, clearing the path for billions of patients around the world to enjoy low risk, high quality care.”
Corti is transforming healthcare by integrating advanced, purpose-built AI into every patient interaction. Its AI seamlessly integrates into virtually any platform, and unlike other co-pilots, it actively supports healthcare professionals by providing real-time prompts, enhancing decision-making throughout their time with patients. It also automates and enhances workflows by removing the need for time-consuming, manual note taking and medical coding – significantly reducing administrative burdens and minimizing errors by up to 40 percent.
Setting it apart from other AI models built on open-source data, Corti’s platform is backed by eight years of research and uses rigorously verified healthcare data, making it the most trustworthy AI support tool available. Processing over 100 million patient interactions every year, Corti is proving to be an indispensable, global asset in delivering high-quality, personalized care.
Chad Compton, Chief Revenue Officer at Corti, added: “I’m thrilled to join Corti at such a pivotal moment in the future of healthcare. We’re already powering millions of patient interactions every year, and this is just the beginning. Corti is redefining how AI can enhance every corner of healthcare by delivering trusted, real-time support in every patient encounter. Our mission to expand Corti’s high-quality AI technology to more healthcare providers worldwide addresses an urgent need, and I am excited to be a part of driving this change.”
Frederik Brabant, Chief Medical Strategy Officer at Corti, said: “After years of treating individual patients, I realized I could improve the lives of millions if I scaled my efforts beyond the bedside. By reducing administrative burden through safe and effective AI, Corti is relieving healthcare professionals of the immense pressure I once experienced as a physician. I’m looking forward to being part of a team allowing healthcare professionals like me to focus on what truly matters – caring for patients.”
Yvonne Kirsch, Corti’s VP Partnerships North America, said: “Joining Corti in North America amid our exponential growth in the US has been momentous. More providers are seeing the immense potential of Corti’s AI – not just for their bottom line, but for easing burnout among overburdened healthcare professionals. Feedback has been overwhelmingly positive, and I’m excited to bring on more strategic partners to extend this technology to thousands more who need it.”
For more information, please visit: www.corti.ai。![图片](https://ai-techpark.com/wp-content/uploads/2024/09/Corti-Stren-960x540.jpg){ width=60% }

---

```
---
感谢阅读！如果您对AI的更多资讯感兴趣，可以查看更多AI文章：[GPTNB](https://gptnb.com)。